# Generated by Django 4.2.7 on 2025-10-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_remove_email_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='assignment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin assignation'),
        ),
        migrations.AddField(
            model_name='participant',
            name='assignment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date début assignation'),
        ),
    ]
