# Generated by Django 4.2.7 on 2025-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_add_assignment_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='language',
        ),
        migrations.AddField(
            model_name='participant',
            name='languages',
            field=models.JSONField(default=list, verbose_name='Langues parlées'),
        ),
    ]
