# Generated by Django 4.2.7 on 2025-10-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_change_language_to_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='languages',
        ),
        migrations.AddField(
            model_name='participant',
            name='language',
            field=models.CharField(default='Français', max_length=50, verbose_name='Langue'),
        ),
    ]
