# Generated by Django 4.2.7 on 2025-10-09 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du stage')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('instructor', models.CharField(max_length=100, verbose_name='Encadrant principal')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité maximale')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Participants actuels')),
                ('constraints', models.JSONField(blank=True, default=list, verbose_name='Contraintes spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('age', models.PositiveIntegerField(verbose_name='Âge')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='Langue')),
                ('status', models.CharField(choices=[('student', 'Élève'), ('instructor', 'Enseignant-e'), ('professional', 'Professionnel-le'), ('staff', 'Salarié-e')], max_length=20, verbose_name='Statut')),
                ('assigned_bungalow_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Bungalow assigné')),
                ('assigned_bed', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lit assigné')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='participants.stage', verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('email', 'stage')},
            },
        ),
    ]
