# Generated by Django 4.2.7 on 2025-10-09 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Village A'), ('B', 'Village B'), ('C', 'Village C')], max_length=1, unique=True, verbose_name='Nom du village')),
                ('amenities_type', models.CharField(choices=[('shared', 'Douches/Toilettes Communes'), ('private', 'Salle de douche + WC privés')], max_length=10, verbose_name="Type d'équipements")),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='participant',
            name='assigned_bungalow_id',
        ),
        migrations.CreateModel(
            name='Bungalow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du bungalow')),
                ('type', models.CharField(choices=[('A', 'Type A - 3 lits simples'), ('B', 'Type B - 1 lit simple + 1 lit double')], max_length=1, verbose_name='Type de bungalow')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité totale')),
                ('occupancy', models.PositiveIntegerField(default=0, verbose_name='Occupation actuelle')),
                ('beds', models.JSONField(default=list, verbose_name='Configuration des lits')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='Équipements')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bungalows', to='participants.village', verbose_name='Village')),
            ],
            options={
                'verbose_name': 'Bungalow',
                'verbose_name_plural': 'Bungalows',
                'ordering': ['village__name', 'name'],
                'unique_together': {('village', 'name')},
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='assigned_bungalow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_participants', to='participants.bungalow', verbose_name='Bungalow assigné'),
        ),
    ]
