# Generated by Django 4.2.7 on 2025-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_add_villages_and_bungalows'),
    ]

    operations = [
        # Étape 1: Supprimer la contrainte unique_together AVANT de supprimer le champ
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        # Étape 2: Ajouter le nouveau champ ManyToMany
        migrations.AddField(
            model_name='participant',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='participants', to='participants.stage', verbose_name='Stages'),
        ),
        # Étape 3: Supprimer l'ancien champ ForeignKey
        migrations.RemoveField(
            model_name='participant',
            name='stage',
        ),
    ]
