# Generated by Django 4.2.7 on 2025-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_change_stage_to_manytomany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
