# Generated by Django 4.2.7 on 2025-11-04 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participants', '0007_remove_participant_languages_participant_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code ISO de la langue (ex: fr, en, es)', max_length=10, unique=True, verbose_name='Code de la langue')),
                ('name', models.CharField(help_text='Nom complet de la langue (ex: Français, English)', max_length=100, verbose_name='Nom de la langue')),
                ('native_name', models.CharField(blank=True, help_text='Nom de la langue dans sa langue native', max_length=100, verbose_name='Nom natif')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la langue est disponible pour sélection', verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans les listes (plus petit = plus haut)", verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_languages', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
