# Generated by Django 4.2.7 on 2025-11-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='participants', to='participants.language', verbose_name='Langues parlées'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='language',
            field=models.CharField(default='Français', max_length=50, verbose_name='Langue principale'),
        ),
    ]
