# Generated by Django 4.2.7 on 2025-11-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_participant_languages_alter_participant_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='event_type',
            field=models.CharField(choices=[('stage', 'Stage'), ('resident', 'Résident'), ('autres', 'Autres')], default='stage', max_length=20, verbose_name="Type d'événement"),
        ),
        migrations.AddField(
            model_name='stage',
            name='instructor2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Encadrant 2'),
        ),
        migrations.AddField(
            model_name='stage',
            name='instructor3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Encadrant 3'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Encadrant principal'),
        ),
    ]
