# Generated by Django 4.2.7 on 2025-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_stage_event_type_stage_instructor2_stage_instructor3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='musicians_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de musiciens'),
        ),
    ]
