# Generated by Django 4.2.7 on 2025-11-04 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participants', '0011_stage_musicians_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('assign', 'Assignation'), ('unassign', 'Désassignation')], max_length=20, verbose_name="Type d'action")),
                ('model_name', models.CharField(choices=[('Stage', 'Événement'), ('Participant', 'Participant'), ('Bungalow', 'Bungalow'), ('Village', 'Village'), ('Language', 'Langue')], max_length=50, verbose_name='Modèle concerné')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('object_repr', models.CharField(max_length=200, verbose_name="Représentation de l'objet")),
                ('description', models.TextField(verbose_name="Description de l'action")),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Stocke les valeurs avant/après pour les modifications', verbose_name='Détails des changements')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Historique d'activité",
                'verbose_name_plural': 'Historique des activités',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='participant_timesta_1b3330_idx'), models.Index(fields=['user', '-timestamp'], name='participant_user_id_c7aba4_idx'), models.Index(fields=['model_name', '-timestamp'], name='participant_model_n_145365_idx')],
            },
        ),
    ]
