# Generated by Django 4.2.7 on 2025-11-23 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participants', '0012_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='stages',
        ),
        migrations.AddField(
            model_name='participant',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalité'),
        ),
        migrations.CreateModel(
            name='ParticipantStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('musician', 'Musicien'), ('instructor', 'Encadrant'), ('staff', 'Staff')], default='participant', max_length=20, verbose_name='Rôle')),
                ('notes', models.TextField(blank=True, help_text='Notes spécifiques à cette participation', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_participant_stages', to=settings.AUTH_USER_MODEL, verbose_name='Inscrit par')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_participations', to='participants.participant', verbose_name='Participant')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_registrations', to='participants.stage', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Inscription participant',
                'verbose_name_plural': 'Inscriptions participants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage', 'participant'], name='participant_stage_i_4754fe_idx'), models.Index(fields=['arrival_date'], name='participant_arrival_223e62_idx'), models.Index(fields=['departure_date'], name='participant_departu_adf9f0_idx')],
                'unique_together': {('participant', 'stage')},
            },
        ),
    ]
