# Generated by Django 4.2.7 on 2025-11-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0014_add_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantstage',
            name='assigned_bed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lit assigné'),
        ),
        migrations.AddField(
            model_name='participantstage',
            name='assigned_bungalow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_stage_assignments', to='participants.bungalow', verbose_name='Bungalow assigné'),
        ),
    ]
