# Generated by Django 4.2.7 on 2025-12-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0015_add_assignment_to_participantstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantstage',
            name='was_forced',
            field=models.BooleanField(default=False, verbose_name='Assignation forcée (conflit accepté)'),
        ),
    ]
